### ISSUE TITLE
Test Coverage BPF Filter

### ISSUE THREAD

**Issue by RJJain** [jatin3893/NetCaPy#4]
To increase the test coverage we can restrict the bpf filter queries .
Even if the underlying  bpf filter allows some filters, inform the users that the filter is not supported by application.
This is because writing tests for all the cases is a cumbersome task.

**Comment by shubhamkank** [comment]
The bpf filter doesn't seem to work when sniffing offline. We can create a tcpdump subprocess in the python code which will do the filtering part. I'm working on it.
